### ISSUE TITLE
Graph ordinate axis range issue

### ISSUE THREAD

**Issue by samuelcolvin** [codecov/frontend#6]
(not sure this is the right question to make future requests/bug reports on issues, apologies if not).

Codecov's graphs look great, but on some projects without a configurable (or more intelligent) Y axis range it doesn't provide any information.

For example coverage on our current project has changed from 95 to 97.5% over the last 2 months, that's important and represents a serious improvement in coverage, but is invisible on a range of 30%:

![codecov.io](http://codecov.io/github/tutorcruncher/TutorCruncher2/branch.svg?token=ed2xRHSlfn&branch=master&limit=40)

Would be great if the y range could be configurable with url args like limit, color etc.

**Comment by stevepeak** [comment]
Thanks @samuelcolvin moved to https://github.com/codecov/support/issues/81
